### PR TITLE
Close when idle option

### PR DESCRIPTION
**Pull request by fandrei**

### CODE REVIEW

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/70/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/71/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, looks ok?

**Comment by mrdavidlaing** [comment]
@fandrei - looks good to me.  Lets merge

**Pull request merged**
