### PR TITLE
Filter nxlog output

### PR DESCRIPTION
**Pull request by fandrei**

### CODE REVIEW

**Comment by le-bott** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/45/

**Build Log**
*last 50 lines*

 ```
[...truncated 280 lines...]
    Expected: "connecting to ingestor.cityindex.logsearch.io:5514"
    But was:  "{Message=connecting to ingestor.cityindex.logsearch.io:5514}"
    -----------^
  
  
  5) Test Failure : LogSearchShipper.Core.Tests.NxLog.NXLogOutputParserTests.ShouldCorrectlyConvertWARNING
       Expected string length 120 but was 87. Strings differ at index 0.
    Expected: "{Message=input file does not exist: \\\\PKH-QAT-APP21\\Logs\\Clie..."
    But was:  "input file does not exist: \\\\PKH-QAT-APP21\\Logs\\ClientPrefere..."
    -----------^
  
  
  6) Test Failure : LogSearchShipper.Core.Tests.NxLog.NXLogOutputParserTests.ShouldExtractLogLevel
       Expected string length 5 but was 4. Strings differ at index 0.
    Expected: "ERROR"
    But was:  "WARN"
    -----------^
  
  at LogSearchShipper.Core.Tests.NxLog.NXLogOutputParserTests.ShouldExtractLogLevel() in c:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\LogsearchShipper.Core.Tests\NxLog\NXLogOutputParserTests.cs:line 88
  
  
C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj(49,3): error MSB3073: The command ""tools\NUnit.Runners.lite.2.6.3.20131019\nunit-console.exe" bin\LogSearchShipper.Core.Tests.dll -result=TestResults.xml -out=TestOutput.log" exited with code 6.
Done Building Project "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj" (Build;RunTests;Package target(s)) -- FAILED.

Build FAILED.

"C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj" (Build;RunTests;Package target) (1) ->
"C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\LogSearchShipper.sln" (Rebuild target) (2) ->
"C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\LogsearchShipper.Core\LogSearchShipper.Core.csproj" (Rebuild target) (3) ->
(CoreCompile target) -> 
  NxLog\NxLogFileWatcher.cs(103,33): warning CS0168: The variable 'fnfe' is declared but never used [C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\LogsearchShipper.Core\LogSearchShipper.Core.csproj]


"C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj" (Build;RunTests;Package target) (1) ->
"C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\LogSearchShipper.sln" (Rebuild target) (2) ->
"C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\IntegrationTests\IntegrationTests.csproj" (Rebuild target) (7) ->
  NxLog\NxLogProcessFileWatcherTests.cs(59,26): warning CS0618: 'log4net.LogManager.GetLoggerRepository()' is obsolete: 'Use GetRepository instead of GetLoggerRepository' [C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\IntegrationTests\IntegrationTests.csproj]
  NxLog\NxLogProcessFileWatcherTests.cs(68,26): warning CS0618: 'log4net.LogManager.GetLoggerRepository()' is obsolete: 'Use GetRepository instead of GetLoggerRepository' [C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\IntegrationTests\IntegrationTests.csproj]


"C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj" (Build;RunTests;Package target) (1) ->
(RunTests target) -> 
  C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj(49,3): error MSB3073: The command ""tools\NUnit.Runners.lite.2.6.3.20131019\nunit-console.exe" bin\LogSearchShipper.Core.Tests.dll -result=TestResults.xml -out=TestOutput.log" exited with code 6.

    3 Warning(s)
    1 Error(s)

Time Elapsed 00:00:13.92
Build step 'Build a Visual Studio project or solution using MSBuild' marked build as failure
```
Test FAILed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/46/Test PASSed.

**Comment by mrdavidlaing** [comment]
@fandrei - code looks great, but please add a positive and negative test for the Category=MISSING_FILE logic.

eg:

```
public void ShouldSetCategoryToMISSING_FILEWhenContains() {
   // 3 asserts that logs containing the required strings set the Category=_
}
public void ShouldNOTSetCategoryWhen() {
   // an assert that a log without the the required strings does not contain Category=MISSING_FILE
}
```

thx.

**Comment by fandrei** [comment]
@mrdavidlaing, done

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/47/Test PASSed.

**Comment by mrdavidlaing** [comment]
Cool.  I'm going to merge this into master, then merge master into issue_66 and get that deployed

**Comment by fandrei** [comment]
@mrdavidlaing, delete this branch?

**Comment by mrdavidlaing** [comment]
Beat you to it

**Comment by fandrei** [comment]
Heh.

**Pull request merged**
