### PR TITLE
Fix service deletion problem 94

### PR DESCRIPTION
**Pull request by fandrei**

### CODE REVIEW

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/148/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/149/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, @ewilde this solves the problem of excessive re-creation of the nxlog service; the service is created on the LSS process startup and deleted on process shutdown.
I've noticed that LSS doesn't shutdown in a case when an attempt to create nxlog service fails. Should I make LSS shutdown in such a case?

**Comment by mrdavidlaing** [comment]
> I've noticed that LSS doesn't exit in a case when an attempt to create nxlog service fails. Should I make LSS shut down in such a case?

@fandrei - yes, I think making LSS shut down / fail to start up is the correct behaviour.  Please change it to be this.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/150/Test PASSed.

**Comment by mrdavidlaing** [comment]
@fandrei - is this ready for merging?

**Comment by fandrei** [comment]
@mrdavidlaing, I need to make it shut down when failed to create the nxlog service, yet. It seems that doing this is not straightforward in Topshelf.
Otherwise it's ready.

**Comment by mrdavidlaing** [comment]
@fandrei - I'm scheduled to deploy v0.12 to all servers tomorrow; so I'd like to get this PR merged ASAP so I can run an overnight test of v0.12.

Could you extract this feature into a new issue please; we can address it in a future release

**Comment by fandrei** [comment]
@mrdavidlaing, done.

**Comment by mrdavidlaing** [comment]
:+1:  Thanks!

**Pull request merged**
