### PR TITLE
Nxlog logging refactoring

### LINKED ISSUE #72: Don't attempt to add nxlog.log data to LogSearchShipper log
It's better to make nxlog itself ship its status logs.

### PR DESCRIPTION
**Pull request by fandrei**
fix #72

### CODE REVIEW

**Comment by le-bott** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/52/

**Build Log**
*last 50 lines*

 ```
[...truncated 227 lines...]
_CopyAppConfigFile:
  Copying file from "App.config" to "..\bin\DummyServiceWithLogRolling.exe.config".
CopyFilesToOutputDirectory:
  Copying file from "obj\Release\DummyServiceWithLogRolling.exe" to "..\bin\DummyServiceWithLogRolling.exe".
  DummyServiceWithLogRolling -> C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\IntegrationTests\bin\DummyServiceWithLogRolling.exe
  Copying file from "obj\Release\DummyServiceWithLogRolling.pdb" to "..\bin\DummyServiceWithLogRolling.pdb".
Done Building Project "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\IntegrationTests\DummyServiceWithLogRolling\DummyServiceWithLogRolling.csproj" (Rebuild target(s)).
Done Building Project "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\LogSearchShipper.sln" (Rebuild target(s)).
RunTests:
  *** NUnit tests beginning...
  "tools\NUnit.Runners.lite.2.6.3.20131019\nunit-console.exe" bin\LogSearchShipper.Core.Tests.dll -result=TestResults.xml -out=TestOutput.log
  NUnit-Console version 2.6.3.13283
  Copyright (C) 2002-2012 Charlie Poole.
  Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
  Copyright (C) 2000-2002 Philip Craig.
  All Rights Reserved.
  
  Runtime Environment - 
     OS Version: Microsoft Windows NT 6.2.9200.0
    CLR Version: 4.0.30319.18449 ( Net 4.5 )
  
  ProcessModel: Default    DomainUsage: Single
  Execution Runtime: net-4.5
  .....................F..........
  Tests run: 31, Errors: 1, Failures: 0, Inconclusive: 0, Time: 7.439864096 seconds
    Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
  
  Errors and Failures:
EXEC : 1) Test error : LogSearchShipper.Core.Tests.NxLog.NxLogProcessManagerTests.ShouldEscapeConfigPathsCorrectly [C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj]
     System.InvalidOperationException : Sequence contains no matching element
     at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
     at LogSearchShipper.Core.Tests.NxLog.NxLogProcessManagerTests.ShouldEscapeConfigPathsCorrectly() in c:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\LogsearchShipper.Core.Tests\NxLog\NxLogProcessManagerTests.cs:line 116
  
  
C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj(49,3): error MSB3073: The command ""tools\NUnit.Runners.lite.2.6.3.20131019\nunit-console.exe" bin\LogSearchShipper.Core.Tests.dll -result=TestResults.xml -out=TestOutput.log" exited with code 1.
Done Building Project "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj" (Build;RunTests;Package target(s)) -- FAILED.

Build FAILED.

"C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj" (Build;RunTests;Package target) (1) ->
(RunTests target) -> 
  EXEC : 1) Test error : LogSearchShipper.Core.Tests.NxLog.NxLogProcessManagerTests.ShouldEscapeConfigPathsCorrectly [C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj]
  C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj(49,3): error MSB3073: The command ""tools\NUnit.Runners.lite.2.6.3.20131019\nunit-console.exe" bin\LogSearchShipper.Core.Tests.dll -result=TestResults.xml -out=TestOutput.log" exited with code 1.

    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:14.25
Build step 'Build a Visual Studio project or solution using MSBuild' marked build as failure
```
Test FAILed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/53/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, so, nxlog logging is working, but I haven't created tests yet.

**Comment by mrdavidlaing** [comment]
@fandrei - ok - I'll get a build of this PR deployed to PPE today so we can at least see if it stops the crashing

**Comment by mrdavidlaing** [comment]
@fandrei I've deployed 1.5.4-dev to LON-WS01186:QAT, PKH-PPE-WEB28 and PKH-PPE-APP62

**Comment by fandrei** [comment]
@mrdavidlaing, are you sure it's deployed? It seems no nxlog status data are reported but my experimental runs. http://api.meta.logsearch.io/_plugin/kibana/index.html#/dashboard/elasticsearch/Andrei-Dev

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/54/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, it's quite tricky to create a precise integration test, as there is no way to detect what records are shipped from the current session; what do you think about adding a unique "session id" for every LogSearchShipper run?

**Comment by mrdavidlaing** [comment]
@fandrei - 
>  are you sure it's deployed? It seems no nxlog status data are reported 

The deployed shippers ship to the cityindex.logsearch.io cluster.  These look like the logs you are after:
http://kibana.cityindex.logsearch.io/#dashboard/temp/AUtto4Zg0iM3i3Y5097b

> what do you think about adding a unique "session id" for every LogSearchShipper run?

I think this is a good idea for an integration test, but probably not for PRODUCTION.

**Comment by fandrei** [comment]
@mrdavidlaing, ah I see.
I can make this feature optional, then.

**Comment by mrdavidlaing** [comment]
:+1:

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/55/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, added an integration test. What do you think?

**Comment by mrdavidlaing** [comment]
@fandrei - looks good - let me deploy this build to QAT & PPE and run it over night.  If all good, then we merge and deploy to all servers tomorrow.

**Comment by mrdavidlaing** [comment]
@fandrei - just deployed the latest build to  LON-WS01186:QAT, PKH-PPE-WEB28 and PKH-PPE-APP62

**Comment by mrdavidlaing** [comment]
@fandrei - it appears that PKH-PPE-APP62 isn't shipping its `LogsearchShipper.log`, even though the CPU metrics are being written to that log file regularly.  

 It did seem to take a long time to Stop the LogsearchShipper service during the upgrade, with the following logs:

```json
{"@timestamp":"2015-02-11T06:14:38.540Z","Message":"[Topshelf] Stopping","logger":"Topshelf.Runtime.Windows.WindowsServiceHost","level":"INFO"}
{"@timestamp":"2015-02-11T06:14:38.541Z","Message":"LogSearchShipperProcessManager.Stop","logger":"LogSearchShipper.Core.LogSearchShipperProcessManager","level":"INFO"}
{"@timestamp":"2015-02-11T06:14:38.541Z","Message":"Stopping Environment Diagram logger...","logger":"LogSearchShipper.Core.LogSearchShipperProcessManager","level":"INFO"}
{"@timestamp":"2015-02-11T06:14:38.541Z","Message":"Stopping EDB file watchers...","logger":"LogSearchShipper.Core.LogSearchShipperProcessManager","level":"INFO"}
{"@timestamp":"2015-02-11T06:14:38.542Z","Message":"Stopping nxlog.exe...","logger":"LogSearchShipper.Core.LogSearchShipperProcessManager","level":"INFO"}
{"@timestamp":"2015-02-11T06:14:38.542Z","Message":"NxLogProcessManager.Stop","logger":"LogSearchShipper.Core.NxLog.NxLogProcessManager","level":"INFO"}
{"@timestamp":"2015-02-11T06:14:38.543Z","Message":"ReportProcessorTimeUsage() finished","logger":"LogSearchShipper.Core.NxLog.NxLogProcessManager","level":"INFO"}
{"@timestamp":"2015-02-11T06:14:38.543Z","Message":"Trying to close nxlog service gracefully","logger":"LogSearchShipper.Core.NxLog.NxLogProcessManager","level":"INFO"}
{"@timestamp":"2015-02-11T06:15:32.567Z","Message":"[Topshelf] Stopped","logger":"Topshelf.Runtime.Windows.WindowsServiceHost","level":"INFO"}
```

I tried restarting the LogsearchShipper service again, but that didn't make a difference (CPU data still being written, but LogsearchShipper.log not being shipped)

My guess is that nxlog has saved the wrong file offset, and we'll only ship data from LogsearchShipper.log file again once the file grows large enough (or is rotated).  Lets wait and see

**Comment by fandrei** [comment]
@PKH-PPE-APP62, it seems PKH-PPE-APP62 is shipping CPU data at this moment.

**Comment by fandrei** [comment]
@mrdavidlaing, it seems PKH-PPE-APP62 is shipping CPU data at this moment.

**Comment by mrdavidlaing** [comment]
Hmph.  Go figure.

**Comment by fandrei** [comment]
@mrdavidlaing, it seems to be stable so far.

**Comment by mrdavidlaing** [comment]
@fandrei - could you merge this into master, and I will roll it out to all shippers

**Comment by fandrei** [comment]
@mrdavidlaing, done

**Pull request merged**
