### PR TITLE
Reduce nxlog restart count

### PR DESCRIPTION
**Pull request by fandrei**
@mrdavidlaing, how does it look?

### CODE REVIEW

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/144/Test PASSed.

**Comment by mrdavidlaing** [comment]
@fandrei - yep; that looks nice and simple.

Just needs a test - which should also be simple if you inject a mock `INxlogProcessManager` instance.

**Comment by fandrei** [comment]
@mrdavidlaing, I'd prefer to use an integration test if you don't mind.

**Comment by mrdavidlaing** [comment]
I personally think that is the wrong approach; since it could fail for so many reasons unrelated to the bit of code you are testing.

However, @ewilde is more knowledgeable than me in this area, so I will delegate the decision to him.

@ewilde?

**Comment by fandrei** [comment]
@mrdavidlaing, I'm afraid that testing it using a mock nxlog service manager just won't reveal any possible bugs.

**Comment by ewilde** [comment]
@fandrei @mrdavidlaing think there would be a good case for an integration test here. It's hard work to make integration tests reliable, but its usually worth it.

**Comment by mrdavidlaing** [comment]
@fandrei, integration test it is then.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/146/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, added test. What do you think?

It seems we had a discrepancy in fields logic; as field names in the test config here https://github.com/cityindex/LogSearchShipper/blob/master/src/LogsearchShipper.Core.Tests/App.config#L19 contain some chars that are explicitly forbidden here https://github.com/cityindex/LogSearchShipper/blob/master/src/LogsearchShipper.Core/NxLog/NxLogProcessManager.cs#L680
I've created a quick fix to make my tests work https://github.com/cityindex/LogSearchShipper/commit/54dc665ec5f1c16cd3bf4888265552fc1bfe962c
Do you think it's a proper solution?

**Comment by mrdavidlaing** [comment]
@fandrei, @ewilde Just a FYI - integration tests are NOT currently run in the build.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/147/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, added a test as you suggested. How does it look?

**Comment by ewilde** [comment]
@fandrei @mrdavidlaing I've added an issue #132. Maybe we can take a look at this in a future sprint?

**Comment by mrdavidlaing** [comment]
@fandrei - looks good to me.  Lets merge and get it deployed for some stress testing

**Comment by fandrei** [comment]
@mrdavidlaing, done

**Pull request merged**
