### PR TITLE
Nxlog upgrade

### PR DESCRIPTION
**Pull request by fandrei**

### CODE REVIEW

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/64/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/65/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, looks ok to you?

**Comment by mrdavidlaing** [comment]
@fandrei - I deployed this to LON-WS01186:QAT shipper at 10:39Z.

I can see that nxlog 2.9 is being used, and everything else seems normal.

http://kibana.cityindex.logsearch.io/#dashboard/temp/AUwnXNfo-8cCSq8dV3z6

I've also tried shipping to ingestor.meta.logsearch.io with [SSLv3 disabled on the ingestor](http://status.labs.cityindex.com/incidents/d4c740cq3phm), and this worked fine.

So all in all I think this is working as intended.

I'll watch it over the course of today, and if nothing strange happens merge the PR this afternoon.

**Comment by fandrei** [comment]
@mrdavidlaing, should we merge this?

**Comment by mrdavidlaing** [comment]
yes

**Pull request merged**
