### PR TITLE
Issue 114 extra edb data

### PR DESCRIPTION
**Pull request by fandrei**

### CODE REVIEW

**Comment by le-bott** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/133/

**Build Log**
*last 50 lines*

 ```
[...truncated 273 lines...]
  Copying file from "obj\Release\DummyServiceWithLogRolling.pdb" to "..\bin\DummyServiceWithLogRolling.pdb".
Done Building Project "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\IntegrationTests\DummyServiceWithLogRolling\DummyServiceWithLogRolling.csproj" (Rebuild target(s)).
Project "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\LogSearchShipper.sln" (2) is building "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\MtLogTailer\MtLogTailer.csproj" (7:5) on node 1 (Rebuild target(s)).
Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
Done Building Project "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\MtLogTailer\MtLogTailer.csproj" (Rebuild target(s)).
Done Building Project "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\LogSearchShipper.sln" (Rebuild target(s)).
RunTests:
  *** NUnit tests beginning...
  "tools\NUnit.Runners.lite.2.6.3.20131019\nunit-console.exe" bin\LogSearchShipper.Core.Tests.dll -result=TestResults.xml -out=TestOutput.log
  NUnit-Console version 2.6.3.13283
  Copyright (C) 2002-2012 Charlie Poole.
  Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
  Copyright (C) 2000-2002 Philip Craig.
  All Rights Reserved.
  
  Runtime Environment - 
     OS Version: Microsoft Windows NT 6.2.9200.0
    CLR Version: 4.0.30319.18449 ( Net 4.5 )
  
  ProcessModel: Default    DomainUsage: Single
  Execution Runtime: net-4.5
  ..F...................................
  Tests run: 37, Errors: 0, Failures: 1, Inconclusive: 0, Time: 5.14730416 seconds
    Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
  
  Errors and Failures:
  1) Test Failure : LogSearchShipper.Core.Tests.EDBFileWatchParserTests.ShouldGenerateConfiguredFileWatches
       String lengths are both 11. Strings differ at index 0.
    Expected: "environment"
    But was:  "serviceType"
    -----------^
  
  at LogSearchShipper.Core.Tests.EDBFileWatchParserTests.ShouldGenerateConfiguredFileWatches() in c:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\LogsearchShipper.Core.Tests\EDBFileWatchParserTests.cs:line 51
  
  
C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj(49,3): error MSB3073: The command ""tools\NUnit.Runners.lite.2.6.3.20131019\nunit-console.exe" bin\LogSearchShipper.Core.Tests.dll -result=TestResults.xml -out=TestOutput.log" exited with code 1.
Done Building Project "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj" (Build;RunTests;Package target(s)) -- FAILED.

Build FAILED.

"C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj" (Build;RunTests;Package target) (1) ->
(RunTests target) -> 
  C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj(49,3): error MSB3073: The command ""tools\NUnit.Runners.lite.2.6.3.20131019\nunit-console.exe" bin\LogSearchShipper.Core.Tests.dll -result=TestResults.xml -out=TestOutput.log" exited with code 1.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:08.12
Build step 'Build a Visual Studio project or solution using MSBuild' marked build as failure
```
Test FAILed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/134/Test PASSed.

**Comment by fandrei** [comment]
@ryanholder, I've added these fields https://github.com/cityindex/LogSearchShipper/blob/issue_114_extra_edb_data/src/LogsearchShipper.Core/EDBFileWatchParser.cs#L127-L155
Have I missed anything?

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/135/Test PASSed.

**Comment by ryanholder** [comment]
@fandrei, that all looks good. It seems all the information for the modal is included in shipper

**Comment by fandrei** [comment]
@ryanholder, let's merge it then.

**Comment by fandrei** [comment]
@mrdavidlaing, when can we deploy it?

**Comment by mrdavidlaing** [comment]
@fandrei - I should get a chance to deploy LSS 1.9.0 today

**Pull request merged**
