### PR TITLE
tweaking diagnostic messages

### PR DESCRIPTION
**Pull request by fandrei**

### CODE REVIEW

**Comment by le-bott** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/131/

**Build Log**
*last 50 lines*

 ```
[...truncated 287 lines...]
  Options:
  /fixture=STR         	Test fixture or namespace to be loaded (Deprecated) (Short format: /load=STR)
  /run=STR             	Name of the test case(s), fixture(s) or namespace(s) to run
  /runlist=STR         	Name of a file containing a list of the tests to run, one per line
  /config=STR          	Project configuration (e.g.: Debug) to load
  /result=STR          	Name of XML result file (Default: TestResult.xml) (Short format: /xml=STR)
  /xmlConsole          	Display XML to the console (Deprecated)
  /noresult            	Suppress XML result output (Short format: /noxml)
  /output=STR          	File to receive test output (Short format: /out=STR)
  /err=STR             	File to receive test error output
  /work=STR            	Work directory for output files
  /labels              	Label each test in stdOut
  /trace=X             	Set internal trace level: Off, Error, Warning, Info, Verbose
  /include=STR         	List of categories to include
  /exclude=STR         	List of categories to exclude
  /framework=STR       	Framework version to be used for tests
  /process=X           	Process model for tests: Single, Separate, Multiple
  /domain=X            	AppDomain Usage for tests: None, Single, Multiple
  /apartment=X         	Apartment for running tests: MTA (Default), STA
  /noshadow            	Disable shadow copy when running in separate domain
  /nothread            	Disable use of a separate thread for tests
  /basepath=STR        	Base path to be used when loading the assemblies
  /privatebinpath=STR  	Additional directories to be probed when loading assemblies, separated by semicolons
  /timeout=X           	Set timeout for each test case in milliseconds
  /wait                	Wait for input before closing console window
  /nologo              	Do not display the logo
  /nodots              	Do not display progress
  /stoponerror         	Stop after the first test failure or error
  /cleanup             	Erase any leftover cache files and exit
  /help                	Display help (Short format: /?)
  
  
  Options that take values may use an equal sign, a colon
  or a space to separate the option from its value.
  
C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj(49,3): error MSB3073: The command ""tools\NUnit.Runners.lite.2.6.3.20131019\nunit-console.exe"  -result=TestResults.xml -out=TestOutput.log" exited with code -1.
Done Building Project "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj" (Build;RunTests;Package target(s)) -- FAILED.

Build FAILED.

"C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj" (Build;RunTests;Package target) (1) ->
(RunTests target) -> 
  C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj(49,3): error MSB3073: The command ""tools\NUnit.Runners.lite.2.6.3.20131019\nunit-console.exe"  -result=TestResults.xml -out=TestOutput.log" exited with code -1.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:17.87
Build step 'Build a Visual Studio project or solution using MSBuild' marked build as failure
```
Test FAILed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/132/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, ok to merge this?

**Comment by mrdavidlaing** [comment]
@fandrei Merge away

**Pull request merged**
