### PR TITLE
Extending config overrides

### PR DESCRIPTION
**Pull request by fandrei**

### CODE REVIEW

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/105/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/106/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, does this look good enough?

**Comment by mrdavidlaing** [comment]
@fandrei - looks good to me.  :+1: for merging

**Comment by fandrei** [comment]
@mrdavidlaing, done

**Pull request merged**
