### PR TITLE
Config overrides

### PR DESCRIPTION
**Pull request by fandrei**

### CODE REVIEW

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/72/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/73/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/74/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/75/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/76/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, looks ok to you?

**Comment by mrdavidlaing** [comment]
@fandrei - looking at the Tests, is it correct to say that currently you can ONLY override `customNxLogConfig` and `closeWhenIdle` settings?

```
<!-- Override watching settings for matched services -->
					<overrideConfigs>
						<overrideConfig forServiceNames="Price" closeWhenIdle="false">
							<customNxLogConfig>
								Exec   if not ($raw_event =~ /DEBUG/ ) drop();
							</customNxLogConfig>
						</overrideConfig>
					</overrideConfigs>
```

That is fine for now; but can you just confirm that if we need to override further settings (eg, a `<field key="key" value="value" />` entry we add that functionality quite easily?

**Comment by fandrei** [comment]
@mrdavidlaing, it should be quite easy to add more options.

**Comment by mrdavidlaing** [comment]
Ok - merge away

**Pull request merged**
