### PR TITLE
Negative name conditions

### PR DESCRIPTION
**Pull request by fandrei**

### CODE REVIEW

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/66/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/67/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, does it look ok?

**Comment by mrdavidlaing** [comment]
@fandrei - could you add some tests please

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/68/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/69/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, looks ok?

**Comment by fandrei** [comment]
@mrdavidlaing, so what do you think?

**Comment by mrdavidlaing** [comment]
:+1: - lets merge

**Pull request merged**
