### PR TITLE
Fix multiple nxlog restarts

### PR DESCRIPTION
**Pull request by fandrei**

### CODE REVIEW

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/56/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, that do you think about this bugfix?

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/57/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, done

**Comment by mrdavidlaing** [comment]
Cool.  I want to wait to see if the recent release of 1.5.4 to all the shippers uncovers any other required changes, otherwise I'll roll this out as part of 1.5.5 early next week.

**Pull request merged**
