### PR TITLE
ship via local file access

### PR DESCRIPTION
**Pull request by fandrei**

### CODE REVIEW

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/121/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/122/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, how does it look?

**Comment by fandrei** [comment]
@mrdavidlaing, ok

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/123/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, done

**Pull request merged**
