### PR TITLE
Mt log tailer

### PR DESCRIPTION
**Pull request by fandrei**

### CODE REVIEW

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/77/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/78/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/79/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, wrt integration. One piece of functionality I've forgotten about is ability to watch files specified by wildcard. Starting working on this...

**Comment by fandrei** [comment]
@mrdavidlaing, I'm not sure how to pass information about the source file from MT tailer to nxlog (when using wildcards, one MT tailer instance can report data from multiple log files). Do you have any ideas?

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/80/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/81/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/82/Test PASSed.

**Comment by fandrei** [comment]
There is a design problem left:
fileWatch elements in LSS let specifying wildcard log file specs, so one element can ship data from multiple log files; and MT log tailer needs to do the same. Currently it logs lines from all input files into the console, so it's impossible to distinguish them. We need some way to pass information about the source file from MT tailer to nxlog.
@mrdavidlaing, @sopel, @dpb587 do you guys have any ideas how to make this in a better way?

**Comment by dpb587** [comment]
I don't really know anything; my idea would be: change MT tailer to prefix all messages with the file path it came from. Then from the nxlog side of things, ensure there's logic between input/output which splits the line up into whatever property/field/variable is typically the file name and the message.

**Comment by mrdavidlaing** [comment]
@fandrei - I think @dpb587's suggestion is a good one; and it will also help in the case of MT log files since they store the date portion of the timestamp in the log filename (I know.  WTF!)

So, as an example, assume the fileWatch element is configured to watch `\\INX-MTLIV01\Logs\MT4\*.log`.

2 log files exist that match that wildcard, with the indented log lines being written:
```
\\INX-MTLIV01\Logs\MT4\20150331.log
    23:59:59 Last log line of the day
\\INX-MTLIV01\Logs\MT4\20150401.log
   00:00:01 First log line of the new day
```

MTLogShipper should ship the following stream:
```
\\INX-MTLIV01\Logs\MT4\20150331.log 23:59:59 Last log line of the day
\\INX-MTLIV01\Logs\MT4\20150401.log 00:00:01 First log line of the new day
```

Then in the log parsers we can turn that info into something sensible (note the timezone conversion from Europe/London time), eg:

```
{ "@timestamp":"2015-03-31T22:59:59Z", "@source.path":"\\INX-MTLIV01\Logs\MT4\20150331.log", "message":"Last log line of the day"}
{ "@timestamp":"2015-03-31T23:00:01Z", "@source.path":"\\INX-MTLIV01\Logs\MT4\20150401.log", "message":"First log line of the new day"}
```

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/83/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/84/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/85/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/86/Test PASSed.

**Comment by le-bott** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/87/

**Build Log**
*last 50 lines*

 ```
[...truncated 224 lines...]
  Deleting file "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\IntegrationTests\bin\DummyServiceWithLogRolling.pdb".
  Deleting file "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\IntegrationTests\DummyServiceWithLogRolling\obj\Release\DummyServiceWithLogRolling.exe".
  Deleting file "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\IntegrationTests\DummyServiceWithLogRolling\obj\Release\DummyServiceWithLogRolling.pdb".
RestorePackages:
  "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\.nuget\NuGet.exe" install "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\IntegrationTests\DummyServiceWithLogRolling\packages.config" -source ""  -NonInteractive  -solutionDir "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\ " 
  All packages listed in packages.config are already installed.
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
CoreCompile:
  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /platform:anycpu32bitpreferred /errorreport:prompt /warn:4 /define:TRACE /highentropyva+ /reference:C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\packages\log4net.2.0.3\lib\net40-full\log4net.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.Linq.dll" /reference:C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\packages\Topshelf.3.1.3\lib\net40-full\Topshelf.dll /reference:C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\packages\Topshelf.Log4Net.3.1.3\lib\net40-full\Topshelf.Log4Net.dll /debug:pdbonly /filealign:512 /optimize+ /out:obj\Release\DummyServiceWithLogRolling.exe /subsystemversion:6.00 /target:exe /utf8output Program.cs Properties\AssemblyInfo.cs "C:\Windows\TEMP\.NETFramework,Version=v4.5.AssemblyAttributes.cs"
_CopyAppConfigFile:
  Copying file from "App.config" to "..\bin\DummyServiceWithLogRolling.exe.config".
CopyFilesToOutputDirectory:
  Copying file from "obj\Release\DummyServiceWithLogRolling.exe" to "..\bin\DummyServiceWithLogRolling.exe".
  DummyServiceWithLogRolling -> C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\IntegrationTests\bin\DummyServiceWithLogRolling.exe
  Copying file from "obj\Release\DummyServiceWithLogRolling.pdb" to "..\bin\DummyServiceWithLogRolling.pdb".
Done Building Project "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\IntegrationTests\DummyServiceWithLogRolling\DummyServiceWithLogRolling.csproj" (Rebuild target(s)).
Project "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\LogSearchShipper.sln" (2) is building "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\MtLogTailer\MtLogTailer.csproj" (9) on node 1 (Rebuild target(s)).
Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
CoreClean:
  Deleting file "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\bin\MtLogTailer.exe.config".
  Deleting file "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\bin\MtLogTailer.exe".
  Deleting file "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\bin\MtLogTailer.pdb".
  Deleting file "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\MtLogTailer\obj\Release\MtLogTailer.exe".
  Deleting file "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\MtLogTailer\obj\Release\MtLogTailer.pdb".
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
CoreCompile:
  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /platform:anycpu32bitpreferred /errorreport:prompt /warn:4 /define:TRACE /highentropyva+ /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.Linq.dll" /debug:pdbonly /filealign:512 /optimize+ /out:obj\Release\MtLogTailer.exe /subsystemversion:6.00 /target:exe /utf8output PathWatcher.cs Program.cs Properties\AssemblyInfo.cs LogShipper.cs "C:\Windows\TEMP\.NETFramework,Version=v4.5.AssemblyAttributes.cs"
LogShipper.cs(94,36): error CS0103: The name '_startOffset' does not exist in the current context [C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\MtLogTailer\MtLogTailer.csproj]
LogShipper.cs(101,11): error CS0103: The name '_startOffset' does not exist in the current context [C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\MtLogTailer\MtLogTailer.csproj]
Done Building Project "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\MtLogTailer\MtLogTailer.csproj" (Rebuild target(s)) -- FAILED.
Done Building Project "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\LogSearchShipper.sln" (Rebuild target(s)) -- FAILED.
Done Building Project "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj" (Build;RunTests;Package target(s)) -- FAILED.

Build FAILED.

"C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj" (Build;RunTests;Package target) (1) ->
"C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\LogSearchShipper.sln" (Rebuild target) (2) ->
"C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\MtLogTailer\MtLogTailer.csproj" (Rebuild target) (9) ->
(CoreCompile target) -> 
  LogShipper.cs(94,36): error CS0103: The name '_startOffset' does not exist in the current context [C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\MtLogTailer\MtLogTailer.csproj]
  LogShipper.cs(101,11): error CS0103: The name '_startOffset' does not exist in the current context [C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\src\MtLogTailer\MtLogTailer.csproj]

    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:13.00
Build step 'Build a Visual Studio project or solution using MSBuild' marked build as failure
```
Test FAILed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/88/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/89/Test PASSed.

**Comment by le-bott** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/90/

**Build Log**
*last 50 lines*

 ```
[...truncated 263 lines...]
  "tools\NUnit.Runners.lite.2.6.3.20131019\nunit-console.exe" bin\LogSearchShipper.Core.Tests.dll -result=TestResults.xml -out=TestOutput.log
  NUnit-Console version 2.6.3.13283
  Copyright (C) 2002-2012 Charlie Poole.
  Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
  Copyright (C) 2000-2002 Philip Craig.
  All Rights Reserved.
  
  Runtime Environment - 
     OS Version: Microsoft Windows NT 6.2.9200.0
    CLR Version: 4.0.30319.18449 ( Net 4.5 )
  
  ProcessModel: Default    DomainUsage: Single
  Execution Runtime: net-4.5
  ....................................
  Tests run: 36, Errors: 0, Failures: 0, Inconclusive: 0, Time: 38.77709216 seconds
    Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
  
Package:
  Packaging binaries into ZIP
  Creating zip file "LogSearchShipper-1.6.0-90.zip".
    added "Configs/EdbNotMatch.config".
    added "Configs/EdbOverridesConfig.config".
    added "log4net.dll".
    added "LogSearchShipper.Core.dll".
    added "LogSearchShipper.exe".
    added "LogSearchShipper.exe.config.SAMPLE".
    added "MtLogTailer.exe".
    added "Newtonsoft.Json.dll".
    added "RunProcess.dll".
    added "Topshelf.dll".
    added "Topshelf.Linux.dll".
    added "Topshelf.Log4Net.dll".
  Created zip file "LogSearchShipper-1.6.0-90.zip" successfully.
Done Building Project "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj" (Build;RunTests;Package target(s)).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:01:36.88
FATAL: No author in changeset b2a9ed1782
java.lang.RuntimeException: No author in changeset b2a9ed1782
	at hudson.plugins.git.GitChangeSet.getAuthor(GitChangeSet.java:323)
	at hudson.model.AbstractBuild.getCulprits(AbstractBuild.java:348)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:673)
	at hudson.model.Run.execute(Run.java:1731)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:232)
```
Test FAILed.

**Comment by le-bott** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/91/

**Build Log**
*last 50 lines*

 ```
[...truncated 264 lines...]
  NUnit-Console version 2.6.3.13283
  Copyright (C) 2002-2012 Charlie Poole.
  Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
  Copyright (C) 2000-2002 Philip Craig.
  All Rights Reserved.
  
  Runtime Environment - 
     OS Version: Microsoft Windows NT 6.2.9200.0
    CLR Version: 4.0.30319.18449 ( Net 4.5 )
  
  ProcessModel: Default    DomainUsage: Single
  Execution Runtime: net-4.5
  ....................................
  Tests run: 36, Errors: 0, Failures: 0, Inconclusive: 0, Time: 43.560191664 seconds
    Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
  
Package:
  Packaging binaries into ZIP
  Creating zip file "LogSearchShipper-1.6.0-91.zip".
    added "Configs/EdbNotMatch.config".
    added "Configs/EdbOverridesConfig.config".
    added "log4net.dll".
    added "LogSearchShipper.Core.dll".
    added "LogSearchShipper.exe".
    added "LogSearchShipper.exe.config.SAMPLE".
    added "MtLogTailer.exe".
    added "Newtonsoft.Json.dll".
    added "RunProcess.dll".
    added "Topshelf.dll".
    added "Topshelf.Linux.dll".
    added "Topshelf.Log4Net.dll".
  Created zip file "LogSearchShipper-1.6.0-91.zip" successfully.
Done Building Project "C:\jenkins\workspace\shared.releases.logsearchshipper-PRs\build.xml.proj" (Build;RunTests;Package target(s)).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:01:16.07
FATAL: No author in changeset b2a9ed1782
java.lang.RuntimeException: No author in changeset b2a9ed1782
	at hudson.plugins.git.GitChangeSet.getAuthor(GitChangeSet.java:323)
	at hudson.model.AbstractBuild.getCulprits(AbstractBuild.java:348)
	at hudson.model.AbstractBuild.getCulprits(AbstractBuild.java:344)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:673)
	at hudson.model.Run.execute(Run.java:1731)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:232)
```
Test FAILed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/94/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/95/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/96/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/97/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/98/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/99/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, I think it's ready enough to try it in the wild. To use a MT tailer, configure log file like this: 

https://github.com/cityindex/LogSearchShipper/pull/90/files#diff-95bd811c9b4bd894763f826b3260250dR18
```
<LogSearchShipper data_folder="data" ingestor_host="ingestor.meta.logsearch.io" ingestor_port="443" sessionId="">
      <fileWatchers>
        <watch files="logs\*.*" type="json" sourceTailer="MT">
        </watch>
      </fileWatchers>
```

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/100/Test PASSed.

**Comment by mrdavidlaing** [comment]
@fandrei - I have deployed a test instance of this LSS, configured like this:

```
<?xml version="1.0" encoding="utf-8"?>

<configuration>
	<configSections>
		<sectionGroup name="LogSearchShipperGroup">
			<section name="LogSearchShipper"
			         type="LogSearchShipper.Core.ConfigurationSections.LogSearchShipperSection, LogSearchShipper.Core"
			         allowLocation="true" allowDefinition="Everywhere" />
		</sectionGroup>
		<section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler, log4net" />
	</configSections>
	<LogSearchShipperGroup>
		<LogSearchShipper data_folder="data" ingestor_host="ingestor.cityindex.logsearch.io" ingestor_port="443"
                      shipper_service_username="CITYINDEX\David.Laing" shipper_service_password="Tuesday6">

			<fileWatchers>
				<watch files="\\INX-SRV-MTDEM01\Apps2\MetaTrader4Server\logs\20150416.log" type="plain" sourceTailer="MT">
					<field key="environment" value="LIVE" />
					<field key="host" value="INX-SRV-MTDEM01" />
					<field key="service" value="MetaTrader4Server" />
				</watch>
			</fileWatchers>

		</LogSearchShipper>
	</LogSearchShipperGroup>
	<log4net>
		<appender name="ConsoleAppender" type="LogSearchShipper.Log4net.DefaultConsoleAppender">
		</appender>
		<appender name="MainLogAppender" type="LogSearchShipper.Log4net.MainLogAppender">
		</appender>
		<appender name="EnvironmentDiagramRollingFileAppender" type="LogSearchShipper.Log4net.EnvironmentDiagramAppender">
		</appender>
		<appender name="EdbExpectedEventSourcesAppender" type="LogSearchShipper.Log4net.EdbExpectedEventSourcesAppender">
		</appender>

		<root>
			<level value="INFO" />
			<appender-ref ref="ConsoleAppender" />
			<appender-ref ref="MainLogAppender" />
			<appender-ref ref="EnvironmentDiagramRollingFileAppender" />
		</root>

		<logger name="EdbExpectedEventSourcesLogger" additivity="false">
			<level value="INFO" />
			<appender-ref ref="EdbExpectedEventSourcesAppender" />
		</logger>

	</log4net>
	<runtime>
		<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
			<dependentAssembly>
				<assemblyIdentity name="log4net" publicKeyToken="669e0ddf0bb1aa2a" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-1.2.13.0" newVersion="1.2.13.0" />
			</dependentAssembly>
		</assemblyBinding>
		<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
			<dependentAssembly>
				<assemblyIdentity name="Topshelf" publicKeyToken="b800c4cfcdeea87b" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-3.1.122.0" newVersion="3.1.122.0" />
			</dependentAssembly>
		</assemblyBinding>
	</runtime>
</configuration>
```

At first glance it seems to be successfully shipping - see http://kibana.cityindex.logsearch.io/#/dashboard/elasticsearch/MetaTrader4Server

**Comment by mrdavidlaing** [comment]
@fandrei - With the above config I’m getting this wierd "'out_file' is not declared” error.

```
2015-04-16 12:23:03 ERROR module 'out_file' is not declared at C:\apps\LogSearchShipper-MT4-test\20150416\data\nxlog.conf:90
2015-04-16 12:23:03 ERROR route route_to_file is not functional without output modules, ignored at C:\apps\LogSearchShipper-MT4-test\20150416\data\nxlog.conf:90
2015-04-16 12:23:03 INFO nxlog-ce-2.9.1347 started
2015-04-16 12:23:03 INFO connecting to ingestor.cityindex.logsearch.io:443
2015-04-16 12:23:03 INFO successfully connected to ingestor.cityindex.logsearch.io:443
```

Any ideas?

**Comment by mrdavidlaing** [comment]
@fandrei - I've bumped into another issue related to startup time of the MT Tailer on an active MT4 log file.

It seems that finding the "end" of a file can take between 10 - 30 minutes
image

The observed effect is that that you start the shipper, and then you don't see any data in Kibana until about 30 min later.

My guess is that reseting the `stream.Position` in this manner is very slow, especially on larger files (which seem to have many MBs of NULLs at the end)

Is there a way we can speed `FindEndOffset()` up?

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/101/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, wrt performance - it seems the .NET Stream buffering isn't working adequately when reading file in reverse order. I'll make a workaround for this.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/102/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, ok - this solves this performance problem. Let's try it?

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/103/Test PASSed.

**Comment by mrdavidlaing** [comment]
@fandrei - just tried out the updated version - 10 min -> 0sec!  :+1: :+1: :+1:

**Comment by fandrei** [comment]
@mrdavidlaing, cool

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/104/Test PASSed.

**Pull request merged**
