### PR TITLE
Trying to fix the problem making LogSearchShipper stop reporting CPU usage 

### PR DESCRIPTION
**Pull request by fandrei**

### CODE REVIEW

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/40/Test PASSed.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/41/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, done. I've tested it a little by freezing the nxlog process using a debugger, but not sure if it works well in the wild.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/42/Test PASSed.

**Comment by mrdavidlaing** [comment]
@fandrei deployed - http://status.labs.cityindex.com/incidents/nk6zqd4r0l3c - 388cfc7

**Comment by mrdavidlaing** [comment]
@fandrei - just to add to the mystery, the QAT shipper came back this AM (without me doing anything).

screen shot 2015-01-19 at 17 15 58

**Comment by fandrei** [comment]
@mrdavidlaing, have you deployed it to all shippers or just a few?

**Comment by fandrei** [comment]
@mrdavidlaing, it came back due to nxlog service restart.

**Comment by mrdavidlaing** [comment]
@fandrei - as per the statuspage incident; its deployed to LON-WS01186:QAT, INX-SRV-APPL79 and RDB-SRV-APP79

**Comment by fandrei** [comment]
ah, I see.

**Comment by mrdavidlaing** [comment]
@fandrei,

It looks like the INX & RDB-SRV-APPL79 shippers stopped reporting CPU data at 15:00Z.

I found the following pattern repeated in the logs:

```
{"@timestamp":"2015-01-20T15:05:56.058Z","Message":"NXLog config file: D:\\Apps\\LogSearchShipper\\data\\nxlog.conf","logger":"LogSearchShipper.Core.NxLog.NxLogProcessManager","level":"INFO"}
{"@timestamp":"2015-01-20T15:05:56.058Z","Message":"NxLogProcessManager.StartNxLogProcess","logger":"LogSearchShipper.Core.NxLog.NxLogProcessManager","level":"INFO"}
{"@timestamp":"2015-01-20T15:05:56.058Z","Message":"Running \"D:\\Apps\\LogSearchShipper\\data\\nxlog\\nxlog.exe\" -c \"D:\\Apps\\LogSearchShipper\\data\\nxlog.conf\" as a service","logger":"LogSearchShipper.Core.NxLog.NxLogProcessManager","level":"INFO"}
{"@timestamp":"2015-01-20T15:05:56.058Z","Message":"Truncating D:\\Apps\\LogSearchShipper\\data\\nxlog.log","logger":"LogSearchShipper.Core.NxLog.NxLogProcessManager","level":"INFO"}
{"@timestamp":"2015-01-20T15:05:56.430Z","Message":"NxLogFileWatcher created","logger":"LogSearchShipper.Core.NxLog.NxLogFileWatcher","level":"INFO"}
{"@timestamp":"2015-01-20T15:05:56.435Z","Message":"ReportProcessorTimeUsage() started","logger":"LogSearchShipper.Core.NxLog.NxLogProcessManager","level":"INFO"}
{"@timestamp":"2015-01-20T15:05:56.435Z","Message":"ReportProcessorTimeUsage() finished","logger":"LogSearchShipper.Core.NxLog.NxLogProcessManager","level":"INFO"}
{"@timestamp":"2015-01-20T15:05:56.454Z","Message":"nxlog-ce-2.8.1248 started","logger":"nxlog.exe","level":"INFO"}
```

Not sure that helps explain what went wrong...

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/44/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, there can be a race condition, I've fixed code to avoid this. Let's try to deploy it.

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/48/Test PASSed.

**Pull request merged**
