### PR TITLE
handling multi-line exception records - issue #102

### PR DESCRIPTION
**Pull request by fandrei**

### CODE REVIEW

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/118/Test PASSed.

**Comment by fandrei** [comment]
https://github.com/cityindex/LogSearchShipper/issues/102

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/124/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, what do you think?

**Comment by mrdavidlaing** [comment]
@fandrei - looks good - just one request:
Can we make it:

```
multilineRule="ci_log4net"
```
rather than 
```
multilineRule="CiLog4net"
```

since then the LSS config matches the `nxlog.conf`

**Comment by le-bott** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.meta.logsearch.io/job/shared.releases.logsearchshipper-PRs/125/Test PASSed.

**Comment by fandrei** [comment]
@mrdavidlaing, looks better?

**Comment by mrdavidlaing** [comment]
Works for me.  Lets get this merged and I'll statr the process of rolling it out

**Comment by fandrei** [comment]
@mrdavidlaing, done

**Pull request merged**
